### ISSUE TITLE
when website is down, launcher doesn't always give input

### ISSUE THREAD

**Issue by h2noob** [iSupersniper/H2Launcher#3]
Issue appeared a little after the downtime of the master login server (I'd say 10 AM GMT on 30th of May).
Launcher wouldn't show up any error message or any window, it would open a process and sit idle in background.
On discord it was mentioned that "php api died for an hour or so"

**Comment by iSupersniper** [comment]
I will handle this in the next update.  Thank you for letting me know.

**Comment by iSupersniper** [comment]
This is now coded in, thank you.  Issue closed.
