### ISSUE TITLE
Login System down?

### ISSUE THREAD

**Issue by Mrvinc911** [iSupersniper/H2Launcher#4]
Every time I try to play a game it asks to log in. I put my correct credentials and it says "Currently Verifying Login" then disappears and I'm stuck at the main screen.

**Comment by iSupersniper** [comment]
Well I can't seem to reproduce this error.  Is the website that it's trying to access being blocked by your antivirus?

**Comment by Mrvinc911** [comment]
Sorry, this was my mistake. I was running the H2Launcher.exe instead of H2Launcher_temp.exe. Using the temp launcher resolved my issue.
